// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oltcuwvgdzszxshpfnre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sdGN1d3ZnZHpzenhzaHBmbnJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzIwNzUsImV4cCI6MjA1ODYwODA3NX0.t6QFQgR2a8MEEap-ajCJEksLEV_Z8WcNSxjSCPROqEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);