
# Project ID to identify the project
project_id = "oltcuwvgdzszxshpfnre"

[api]
# Port number for the API
port = 54321
# Schemas to expose in the API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure
max_rows = 1000

[db]
# Port number for the database
port = 54322
# Database major version
major_version = 15

[studio]
# Port number for the Studio
port = 54323

# Email testing
[inbucket]
# Port number for the email testing interface
port = 54324

[storage]
# Port number for the storage API
port = 54325

[auth]
# Port number for the authentication API
port = 54326

[realtime]
# Port number for the realtime API
port = 54327

[functions]
# Port number for Functions API
port = 54328
[functions.log-action]
verify_jwt = true
