-- Replace knowledge tags with the specific connector-focused categories
DELETE FROM public.knowledge_tags;

INSERT INTO public.knowledge_tags (name, description, count, color) VALUES
('Mission', 'Defining organizational purpose and direction', 15, '#10B981'),
('Vision', 'Creating compelling future states', 18, '#F59E0B'),
('Governance', 'Board and organizational structure', 12, '#8B5CF6'),
('Compliance', 'Meeting legal and regulatory requirements', 8, '#EF4444'),
('Accessibility', 'Creating inclusive experiences for all', 14, '#3B82F6'),
('Budgeting', 'Financial planning and management', 16, '#059669'),
('Grants', 'Securing grant funding', 11, '#EC4899'),
('Sponsorship', 'Corporate and business partnerships', 22, '#F97316'),
('Crowdfunding', 'Online fundraising campaigns', 9, '#6366F1'),
('Donations', 'Individual giving and donor relations', 19, '#84CC16'),
('Volunteers', 'Recruiting and managing volunteers', 25, '#DC2626'),
('Training', 'Skill development and education', 17, '#0891B2'),
('Wellness', 'Health and wellbeing initiatives', 13, '#7C3AED'),
('Conflict', 'Resolution and mediation strategies', 10, '#059669'),
('Onboarding', 'Welcoming new members and volunteers', 16, '#F59E0B'),
('Logistics', 'Event and program coordination', 20, '#8B5CF6'),
('Venues', 'Finding and booking event spaces', 14, '#EF4444'),
('Permits', 'Legal requirements and documentation', 7, '#3B82F6'),
('Tech', 'Technology tools and platforms', 21, '#10B981'),
('Feedback', 'Collecting and using input effectively', 12, '#EC4899'),
('Messaging', 'Crafting compelling communications', 18, '#F97316'),
('Newsletters', 'Email communication strategies', 15, '#6366F1'),
('Social', 'Social media engagement', 24, '#84CC16'),
('Media', 'Press relations and coverage', 11, '#DC2626'),
('Print', 'Physical marketing materials', 8, '#0891B2'),
('Websites', 'Digital presence and online tools', 19, '#7C3AED'),
('Ticketing', 'Event registration and management', 13, '#059669'),
('Analytics', 'Measuring impact and engagement', 16, '#F59E0B'),
('Platforms', 'Digital tools and systems', 17, '#8B5CF6'),
('SMS', 'Text messaging for outreach', 9, '#EF4444'),
('CRM', 'Contact and relationship management', 20, '#3B82F6'),
('Partnerships', 'Building strategic alliances', 22, '#10B981'),
('Sponsors', 'Corporate sponsor relations', 18, '#EC4899'),
('Storytelling', 'Narrative and impact communication', 14, '#F97316'),
('Councils', 'Advisory and governance bodies', 6, '#6366F1'),
('Rituals', 'Community traditions and ceremonies', 12, '#84CC16'),
('Food', 'Catering and hospitality planning', 15, '#DC2626'),
('Traditions', 'Cultural practices and heritage', 10, '#0891B2'),
('Branding', 'Visual identity and messaging', 17, '#7C3AED'),
('Outreach', 'Community engagement and growth', 23, '#059669');