-- Seed lexicon table with industries/market verticals
INSERT INTO lexicon (term, term_type, is_suggested, is_active, usage_count)
VALUES 
  ('Technology & Software', 'industry', true, true, 0),
  ('Healthcare & Medical Services', 'industry', true, true, 0),
  ('Financial Services & Banking', 'industry', true, true, 0),
  ('Manufacturing & Industrial', 'industry', true, true, 0),
  ('Retail & E-commerce', 'industry', true, true, 0),
  ('Real Estate & Property', 'industry', true, true, 0),
  ('Education & Training', 'industry', true, true, 0),
  ('Consulting & Professional Services', 'industry', true, true, 0),
  ('Marketing & Advertising', 'industry', true, true, 0),
  ('Media & Entertainment', 'industry', true, true, 0),
  ('Hospitality & Tourism', 'industry', true, true, 0),
  ('Transportation & Logistics', 'industry', true, true, 0),
  ('Energy & Utilities', 'industry', true, true, 0),
  ('Agriculture & Food Production', 'industry', true, true, 0),
  ('Construction & Engineering', 'industry', true, true, 0),
  ('Telecommunications', 'industry', true, true, 0),
  ('Legal Services', 'industry', true, true, 0),
  ('Insurance', 'industry', true, true, 0),
  ('Pharmaceutical & Biotechnology', 'industry', true, true, 0),
  ('Nonprofit & Social Services', 'industry', true, true, 0),
  ('Government & Public Sector', 'industry', true, true, 0),
  ('Automotive', 'industry', true, true, 0),
  ('Aerospace & Defense', 'industry', true, true, 0),
  ('Consumer Goods', 'industry', true, true, 0),
  ('Sports & Recreation', 'industry', true, true, 0),
  ('Arts & Design', 'industry', true, true, 0),
  ('Environmental Services', 'industry', true, true, 0),
  ('Cybersecurity', 'industry', true, true, 0),
  ('Data Analytics & Business Intelligence', 'industry', true, true, 0),
  ('Cloud Computing & SaaS', 'industry', true, true, 0),
  ('Artificial Intelligence & Machine Learning', 'industry', true, true, 0),
  ('Blockchain & Cryptocurrency', 'industry', true, true, 0),
  ('Gaming & Esports', 'industry', true, true, 0),
  ('Fashion & Apparel', 'industry', true, true, 0),
  ('Beauty & Cosmetics', 'industry', true, true, 0),
  ('Publishing & Journalism', 'industry', true, true, 0),
  ('Architecture & Interior Design', 'industry', true, true, 0),
  ('Human Resources & Recruitment', 'industry', true, true, 0),
  ('Supply Chain & Procurement', 'industry', true, true, 0),
  ('Research & Development', 'industry', true, true, 0)
ON CONFLICT (term, term_type) DO NOTHING;